services:
  graphql:
    build:
      context: ./services/graphql
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./services/graphql:/app
    depends_on:
      - account
      - product
  account:
    build:
      context: .
      dockerfile: ./services/account/Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./services/account:/grpc-sample/services/account
      - ./proto:/grpc-sample/proto
    depends_on:
      - account-db
    environment:
      - DB_HOST=account-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=account
      - GRPC_ADDR=0.0.0.0:9090
  account-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=account
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - account-db:/var/lib/postgresql/data
  product:
    build:
      context: ./services/product
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3002
    volumes:
      - ./services/product:/app
    depends_on:
      - product-db
  product-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
    ports:
      - 5433:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - product-db:/var/lib/postgresql/data
volumes:
  account-db:
  product-db: